Create style
MenendezON/bookstore pull request #5
Opened 2023-08-26 21:02 UTC by MenendezON

This pull request concerns the style of the card of our book.
This app is based on Redux and React

2023-08-26 21:39 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @MenendezON , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media1.giphy.com/media/qQdL532ZANbjy/giphy.gif"/> |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅ Great readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 21:39 UTC, joskalenda commented on src/css/index.css
- [ ] You are is missing the font-family `Montserrat` as per the design, please make sure you add it

2023-08-26 21:39 UTC, joskalenda commented on src/components/BookList.js
> +  const [progress, setProgress] = useState(randomNum);
- [ ] EXPECTED DESIGN

<img width="954" alt="1" src="https://github.com/MenendezON/bookstore/assets/77843050/66cfff1c-ecd9-411b-b43f-7092d41eb554">

- [ ] WHAT YOU DID

<img width="835" alt="2" src="https://github.com/MenendezON/bookstore/assets/77843050/9143e800-0004-4640-b621-bea80478bda7">

1. We have some key parts that are missing in the design as the progress bar percentage, 
2. The style of the progress bar should be identical to the one above on the original template
3. The user icon on the top-right is different from the one on the original design
4. The bookstore title is not well aligned as the above is showing 

<img width="386" alt="3" src="https://github.com/MenendezON/bookstore/assets/77843050/800aed9e-03f0-45f5-a05f-7969d2824777">

1. Make sure you fix this text brightness, I think your color is more blue than the one on the original design

<img width="322" alt="5" src="https://github.com/MenendezON/bookstore/assets/77843050/d53ef210-40e5-4138-b32a-1fd6f34c2764">

1. Please add a space around your update button as per the design above

2023-08-26 21:39 UTC, joskalenda commented on src/components/BookForm.js
- [ ] EXPECTED DESIGN

<img width="950" alt="6" src="https://github.com/MenendezON/bookstore/assets/77843050/95647b81-f4ac-4227-8329-acb19a633f9a">

- [ ] WHAT YOU DID
<img width="861" alt="7" src="https://github.com/MenendezON/bookstore/assets/77843050/0bd03e6b-7bae-4581-9f8a-b750a649ca9b">

1. We have 3 inputs forms, the first one is larger than the others and is the placeholder of `Book title`
2. The second one is a category and it is a dropdown selected button with the placeholder of category, not the author

2023-08-27 00:13 UTC, ademibowale approved these changes
Hi @MenendezON  , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️
- Styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/)✔️
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-27 00:28 UTC, MenendezON commented
Hi @ademibowale , thank you for your feedback but I'm facing a problem. This project was my core req to complete my week. I have my feedback now but it is too late to submit it completely, what can I do to not repeat this block?

2023-08-27 00:28 UTC, merged

2023-08-27 01:39 UTC, ademibowale commented
@MenendezON Write the student success to assist you on that as long as your project has been approved and no activities has left uncompleted that might help you out